"use client";

import { useEffect, useState } from "react";
import type { AppContext } from "@/components/design-system-app";
import { Icon } from "@/components/icons";
import type { Asset, ContentPage, ContentSection, PageType, Release } from "@/types/content";

const studioNav = [["dashboard","grid","Dashboard"],["content","file","Content"],["tokens","layers","Tokens"],["assets","image","Assets"],["releases","file","Releases"],["feedback","edit","Feedback"],["settings","settings","Settings"]] as const;

export function Studio({ app }: { app: AppContext }) {
  const [logged, setLogged] = useState(false);
  useEffect(()=>{const timer=window.setTimeout(()=>setLogged(sessionStorage.getItem("studio-auth")==="yes"),0);return()=>window.clearTimeout(timer)},[]);
  if (app.path === "/studio/login" || !logged) return <Login onLogin={()=>{sessionStorage.setItem("studio-auth","yes");setLogged(true);app.navigate("/studio/dashboard")}}/>;
  const parts=app.path.split("/").filter(Boolean); const section=parts[1]||"dashboard";
  return <div className="studio-shell"><aside className="studio-sidebar"><button className="brand studio-brand" onClick={()=>app.navigate("/studio/dashboard")}><span className="brand-mark">N</span><span>Design Studio</span></button><nav>{studioNav.map(([slug,icon,label])=><button key={slug} className={section===slug?"active":""} onClick={()=>app.navigate(`/studio/${slug}`)}><Icon name={icon}/>{label}</button>)}</nav><div className="studio-sidebar-bottom"><button onClick={()=>app.navigate("/")}><Icon name="external"/>View portal</button><div className="admin-chip"><span>AD</span><div><strong>Administrator</strong><small>Full access</small></div></div></div></aside><div className="studio-main">{section==="dashboard"?<Dashboard app={app}/>:section==="content"?<ContentManager app={app} parts={parts}/>:section==="tokens"?<Tokens app={app}/>:section==="assets"?<AssetsManager app={app}/>:section==="releases"?<ReleasesManager app={app}/>:section==="feedback"?<Feedback/>:<Settings app={app}/>}</div></div>;
}

function Login({onLogin}:{onLogin:()=>void}) { const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); return <div className="login-page"><div className="login-brand"><span className="brand-mark">N</span><span>Nusa Design System</span></div><form onSubmit={(e)=>{e.preventDefault();onLogin()}}><span className="eyebrow">Administrator</span><h1>Welcome back.</h1><p>Kelola dokumentasi, token, dan aset dalam satu tempat.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="admin@company.com" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="••••••••" required/></label><button className="primary-button" type="submit">Sign in <Icon name="arrow"/></button><small>Untuk versi demo, gunakan email dan password apa pun. Hubungkan Supabase Auth sebelum produksi.</small></form><div className="login-art"><div><span>Documentation</span><strong>Clear guidance.<br/>One source.</strong></div></div></div> }

function StudioHeader({eyebrow,title,action}:{eyebrow:string;title:string;action?:React.ReactNode}) { return <header className="studio-header"><div><span>{eyebrow}</span><h1>{title}</h1></div>{action&&<div>{action}</div>}</header> }

function Dashboard({app}:{app:AppContext}) { const drafts=app.data.pages.filter(p=>p.status==="draft"); return <div className="studio-page"><StudioHeader eyebrow="Sunday, 19 July" title="Good morning." action={<button className="primary-button" onClick={()=>app.navigate("/studio/content/new")}><Icon name="plus"/>New documentation</button>}/><section className="dashboard-grid"><article className="continue-card"><span className="eyebrow">Continue working</span><div className="big-number">{drafts.length||3}</div><h2>Drafts need your attention</h2><p>Continue editing and publish when the guidance is ready.</p><button onClick={()=>app.navigate("/studio/content")}>View drafts <Icon name="arrow"/></button></article><article><span className="eyebrow">Documentation health</span><div className="health-ring"><strong>86%</strong></div><p>Most published pages include the recommended guidance.</p></article><article><span className="eyebrow">Token library</span><div className="big-number">2,711</div><h2>Tokens available</h2><p>21 descriptions complete · 840 references found</p><button onClick={()=>app.navigate("/studio/tokens")}>Open tokens <Icon name="arrow"/></button></article></section><section className="attention-list"><div className="section-heading-small"><div><span className="eyebrow">Needs attention</span><h2>Keep the system healthy.</h2></div></div>{[["3 pages","Missing accessibility guidance"],["12 assets","Need alternative text"],["1 token import","Ready to review"]].map(([n,t])=><button key={t}><strong>{n}</strong><span>{t}</span><Icon name="chevron"/></button>)}</section><section className="recent-table"><div className="section-heading-small"><h2>Recently updated</h2><button onClick={()=>app.navigate("/studio/content")}>View all</button></div>{app.data.pages.slice(0,5).map(p=><div key={p.id}><span className="item-icon">{p.title.slice(0,1)}</span><strong>{p.title}</strong><span>{p.type}</span><em className={`status ${p.status}`}>{p.status}</em><small>{p.updatedAt}</small><button onClick={()=>app.navigate(`/studio/content/${p.id}/edit`)}><Icon name="edit"/></button></div>)}</section></div> }

function ContentManager({app,parts}:{app:AppContext;parts:string[]}) { const [query,setQuery]=useState(""); const [type,setType]=useState("all"); const pageId=parts[2]; if(pageId==="new") return <PageEditor app={app}/>; if(pageId&&parts[3]==="edit") { const page=app.data.pages.find(p=>p.id===pageId); return page?<PageEditor app={app} initial={page}/>:null; }
  const list=app.data.pages.filter(p=>(type==="all"||p.type===type)&&`${p.title} ${p.category}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="studio-page"><StudioHeader eyebrow="Content" title="Documentation" action={<button className="primary-button" onClick={()=>app.navigate("/studio/content/new")}><Icon name="plus"/>New page</button>}/><div className="manager-toolbar"><label className="search-field"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search documentation..."/></label><select value={type} onChange={e=>setType(e.target.value)}><option value="all">All types</option><option value="foundation">Foundations</option><option value="component">Components</option><option value="pattern">Patterns</option><option value="resource">Resources</option></select></div><div className="content-table table-head"><span>Page</span><span>Type</span><span>Status</span><span>Updated</span><span/></div>{list.map(p=><div className="content-table" key={p.id}><button className="page-cell" onClick={()=>app.navigate(`/studio/content/${p.id}/edit`)}><span className="item-icon">{p.title[0]}</span><div><strong>{p.title}</strong><small>{p.category}</small></div></button><span>{p.type}</span><em className={`status ${p.status}`}>{p.status}</em><span>{p.updatedAt}</span><div className="row-actions"><button onClick={()=>duplicatePage(app,p)} title="Duplicate"><Icon name="copy"/></button><button onClick={()=>archivePage(app,p)} title="Archive"><Icon name="trash"/></button></div></div>)}</div> }

function PageEditor({app,initial}:{app:AppContext;initial?:ContentPage}) { const isNew=!initial; const template=initial||{id:"new-page",type:"component" as PageType,title:"Untitled component",slug:"untitled-component",summary:"Jelaskan tujuan dan kapan component ini digunakan.",category:"General",status:"draft" as const,maturity:"experimental" as const,version:"1.0",owner:"Design System Team",updatedAt:"19 Jul 2026",sections:[]}; const [page,setPage]=useState<ContentPage>(structuredClone(template)); const [selected,setSelected]=useState<string|null>(page.sections[0]?.id||null); const [saved,setSaved]=useState(true);
  const update=(patch:Partial<ContentPage>)=>{setPage(p=>({...p,...patch}));setSaved(false)}; const save=(publish=false)=>{const next={...page,status:publish?"published" as const:page.status,updatedAt:"19 Jul 2026"};app.setData(d=>({...d,pages:isNew?[...d.pages,next]:d.pages.map(p=>p.id===next.id?next:p)}));setPage(next);setSaved(true);if(isNew)app.navigate(`/studio/content/${next.id}/edit`)};
  const section=page.sections.find(s=>s.id===selected);
  return <div className="editor-shell"><header className="editor-top"><div><button onClick={()=>app.navigate("/studio/content")}>Content</button><span>/</span><strong>{page.title}</strong></div><div className="save-state"><span className={saved?"saved":"unsaved"}/>{saved?"Saved":"Unsaved changes"}</div><div><button className="secondary-button" onClick={()=>window.open(`/${page.type}s/${page.slug}`,"_blank")}>Preview</button><button className="primary-button" onClick={()=>save(true)}>Publish</button></div></header><aside className="editor-outline"><div><span>Page outline</span><button onClick={()=>addSection(page,setPage,setSelected)}><Icon name="plus"/></button></div>{page.sections.map((s,i)=><button key={s.id} className={selected===s.id?"active":""} onClick={()=>setSelected(s.id)}><span>{String(i+1).padStart(2,"0")}</span>{s.title}<i/></button>)}{!page.sections.length&&<div className="outline-empty"><p>No sections yet.</p><button onClick={()=>addRecommended(page,setPage,setSelected)}>Add recommended sections</button></div>}</aside><main className="editor-canvas"><div className="editable-header"><span className="eyebrow">{page.category}</span><input className="title-input" value={page.title} onChange={e=>update({title:e.target.value,slug:e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-")})}/><textarea value={page.summary} onChange={e=>update({summary:e.target.value})}/><div className="meta-row"><span className="status-dot"/>{page.maturity}<span>v{page.version}</span></div></div>{page.sections.map(s=><button className={`editable-block ${selected===s.id?"selected":""}`} key={s.id} onClick={()=>setSelected(s.id)}><span className="drag-handle">⋮⋮</span><span className="block-type">{s.kind}</span><h2>{s.title}</h2>{s.body&&<p>{s.body}</p>}{s.items&&<div className="mini-item-grid">{s.items.map(i=><span key={i.title}>{i.title}</span>)}</div>}</button>)}<button className="add-block" onClick={()=>addSection(page,setPage,setSelected)}><Icon name="plus"/>Type / to add a block</button></main><aside className="editor-properties"><div className="property-tabs"><button className="active">Block</button><button>Page</button><button>Checks</button></div>{section?<SectionProperties section={section} page={page} setPage={(p)=>{setPage(p);setSaved(false)}} onDelete={()=>{setPage(p=>({...p,sections:p.sections.filter(s=>s.id!==section.id)}));setSelected(null);setSaved(false)}}/>:<PageProperties page={page} update={update}/>}</aside></div> }

function SectionProperties({section,page,setPage,onDelete}:{section:ContentSection;page:ContentPage;setPage:(p:ContentPage)=>void;onDelete:()=>void}) { const update=(patch:Partial<ContentSection>)=>setPage({...page,sections:page.sections.map(s=>s.id===section.id?{...s,...patch}:s)}); return <div className="properties-form"><label>Section title<input value={section.title} onChange={e=>update({title:e.target.value})}/></label><label>Guidance<textarea rows={8} value={section.body||""} onChange={e=>update({body:e.target.value})} placeholder="Write clear guidance for designers..."/></label><div className="property-group"><span>Visibility</span><button className="option-row"><span>Visible on portal</span><i className="toggle on"/></button></div><div className="writing-tip"><strong>Writing tip</strong><p>Gunakan kalimat singkat. Jelaskan apa yang perlu dilakukan dan mengapa.</p></div><button className="danger-button" onClick={onDelete}><Icon name="trash"/>Remove block</button></div> }
function PageProperties({page,update}:{page:ContentPage;update:(p:Partial<ContentPage>)=>void}) { return <div className="properties-form"><label>Page type<select value={page.type} onChange={e=>update({type:e.target.value as PageType})}><option>component</option><option>foundation</option><option>pattern</option><option>resource</option></select></label><label>Category<input value={page.category} onChange={e=>update({category:e.target.value})}/></label><label>Owner<input value={page.owner} onChange={e=>update({owner:e.target.value})}/></label></div> }

function addSection(page:ContentPage,setPage:(p:ContentPage)=>void,setSelected:(id:string)=>void){const id=`section-${Date.now()}`;setPage({...page,sections:[...page.sections,{id,kind:"rich-text",title:"New section",body:"Add guidance that is easy for designers to understand."}]});setSelected(id)}
function addRecommended(page:ContentPage,setPage:(p:ContentPage)=>void,setSelected:(id:string)=>void){const names=page.type==="component"?["Overview","Visual preview","Anatomy","Variants","Sizes","States","Behavior","Content guidelines","Responsive behavior","Accessibility","Do & don’t","Related components","Figma resource","Changelog"]:["Overview","Principles","Token collection","Hierarchy","Usage","Examples","Accessibility","Do & don’t","Related foundations","Figma resource","Changelog"];const sections=names.map((n,i)=>({id:`section-${i}`,kind:(i===0?"overview":"rich-text") as ContentSection["kind"],title:n,body:"Add clear guidance for designers."}));setPage({...page,sections});setSelected(sections[0].id)}
function duplicatePage(app:AppContext,p:ContentPage){const copy={...structuredClone(p),id:`${p.id}-copy-${Date.now()}`,title:`${p.title} copy`,slug:`${p.slug}-copy`,status:"draft" as const};app.setData(d=>({...d,pages:[...d.pages,copy]}))}
function archivePage(app:AppContext,p:ContentPage){if(confirm(`Archive ${p.title}?`))app.setData(d=>({...d,pages:d.pages.map(x=>x.id===p.id?{...x,status:"archived"}:x)}))}

function Tokens({app}:{app:AppContext}) { const [fileName,setFileName]=useState("token-dari-figma.json"); const groups=[["Color","1,664"],["Dimension","492"],["String","363"],["Font style","69"],["Number","69"],["Gradient","43"],["Grid","6"],["Effect","5"]]; return <div className="studio-page"><StudioHeader eyebrow="Tokens" title="Token library" action={<label className="primary-button upload-button"><Icon name="upload"/>Import JSON<input type="file" accept=".json" onChange={e=>{if(e.target.files?.[0])setFileName(e.target.files[0].name)}}/></label>}/><section className="token-summary"><article><span>Active source</span><h2>{fileName}</h2><p>Figma Design Tokens format</p><em className="status published">Published</em></article><article><span>Total tokens</span><strong>2,711</strong><p>Across 9 collections</p></article><article><span>References</span><strong>840</strong><p>345 unique references</p></article><article><span>Descriptions</span><strong>21</strong><p>2,690 still need guidance</p></article></section><div className="token-workspace"><aside><button className="active">All tokens <span>2,711</span></button>{["Core","Alias","Element","Color","Typography","Gradient","Grid","Effect"].map(g=><button key={g}>{g}<Icon name="chevron"/></button>)}</aside><section><div className="manager-toolbar"><label className="search-field"><Icon name="search"/><input placeholder="Search token name..."/></label><button className="secondary-button">Filters</button></div><div className="token-group-grid">{groups.map(([n,c])=><article key={n}><div className={`token-preview token-${n.toLowerCase().replace(" ","-")}`}>{n.slice(0,2)}</div><h3>{n}</h3><strong>{c}</strong><p>tokens available</p><button>Explore <Icon name="arrow"/></button></article>)}</div></section></div></div> }

function AssetsManager({app}:{app:AppContext}) { const [type,setType]=useState("all"); const [selected,setSelected]=useState<Asset|null>(null); const list=app.data.assets.filter(a=>type==="all"||a.type===type); return <div className="studio-page"><StudioHeader eyebrow="Assets" title="Asset Library" action={<button className="primary-button" onClick={()=>{const a:Asset={id:`asset-${Date.now()}`,type:"icon",name:"New icon",slug:`new-icon-${Date.now()}`,category:"Actions",brand:"Shared",status:"draft",description:"Add a clear description.",keywords:[],glyph:"○",version:"1.0",updatedAt:"19 Jul 2026"};app.setData(d=>({...d,assets:[...d.assets,a]}));setSelected(a)}}><Icon name="upload"/>Add asset</button>}/><div className="asset-manager-tabs">{["all","icon","icon-illustration","illustration","logo","brand-asset","template","download"].map(t=><button className={type===t?"active":""} key={t} onClick={()=>setType(t)}>{t.replace("-"," ")}</button>)}</div><div className="asset-manager-grid">{list.map(a=><button key={a.id} onClick={()=>setSelected(a)}><div><span>{a.glyph}</span></div><strong>{a.name}</strong><small>{a.category} · {a.brand}</small><em className={`status ${a.status}`}>{a.status}</em></button>)}</div>{selected&&<AssetEditor asset={selected} app={app} close={()=>setSelected(null)}/>}</div> }
function AssetEditor({asset,app,close}:{asset:Asset;app:AppContext;close:()=>void}){const [item,setItem]=useState(asset);const save=()=>{app.setData(d=>({...d,assets:d.assets.map(a=>a.id===item.id?item:a)}));close()};return <div className="drawer-backdrop" onClick={close}><aside className="asset-editor" onClick={e=>e.stopPropagation()}><header><h2>Edit asset</h2><button onClick={close}><Icon name="close"/></button></header><div className="asset-edit-preview"><span>{item.glyph}</span></div><div className="properties-form"><label>Name<input value={item.name} onChange={e=>setItem({...item,name:e.target.value})}/></label><label>Type<select value={item.type} onChange={e=>setItem({...item,type:e.target.value as Asset["type"]})}>{["icon","icon-illustration","illustration","logo","brand-asset","template","download"].map(x=><option key={x}>{x}</option>)}</select></label><label>Brand<select value={item.brand} onChange={e=>setItem({...item,brand:e.target.value as Asset["brand"]})}>{["Shared","IM3","Indosat","Tri","Partner"].map(x=><option key={x}>{x}</option>)}</select></label><label>Description<textarea value={item.description} onChange={e=>setItem({...item,description:e.target.value})}/></label><label>Preview glyph<input value={item.glyph} onChange={e=>setItem({...item,glyph:e.target.value})}/></label><button className="primary-button" onClick={save}>Save asset</button></div></aside></div>}

function ReleasesManager({app}:{app:AppContext}){const create=()=>{const r:Release={id:`r-${Date.now()}`,version:"1.1",title:"Untitled release",summary:"Jelaskan perubahan yang perlu diketahui designer.",date:"19 Jul 2026",status:"draft",changes:[]};app.setData(d=>({...d,releases:[...d.releases,r]}))};return <div className="studio-page"><StudioHeader eyebrow="Releases" title="Changelog" action={<button className="primary-button" onClick={create}><Icon name="plus"/>New release</button>}/><div className="release-manager">{app.data.releases.map(r=><article key={r.id}><div><span>v{r.version}</span><em className={`status ${r.status}`}>{r.status}</em></div><h2>{r.title}</h2><p>{r.summary}</p><time>{r.date}</time><button className="secondary-button">Edit release</button></article>)}</div></div>}
function Feedback(){return <div className="studio-page"><StudioHeader eyebrow="Feedback" title="What designers are saying"/><div className="empty-panel"><Icon name="edit"/><h2>No open feedback</h2><p>Feedback from portal pages will appear here.</p></div></div>}
function Settings({app}:{app:AppContext}){const [settings,setSettings]=useState(app.data.settings);return <div className="studio-page settings-page"><StudioHeader eyebrow="Settings" title="Portal settings"/><div className="settings-layout"><aside>{["General","Branding","Navigation","Templates","Administrator","Visibility","Backup & export","Audit log"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</aside><section><h2>General</h2><p>Atur identitas dasar yang muncul di seluruh portal.</p><div className="properties-form"><label>Design system name<input value={settings.name} onChange={e=>setSettings({...settings,name:e.target.value})}/></label><label>Hero statement<input value={settings.tagline} onChange={e=>setSettings({...settings,tagline:e.target.value})}/></label><label>Description<textarea rows={5} value={settings.description} onChange={e=>setSettings({...settings,description:e.target.value})}/></label><label>Portal visibility<select value={settings.visibility} onChange={e=>setSettings({...settings,visibility:e.target.value as "public"|"unlisted"})}><option value="unlisted">Unlisted — no login, no search indexing</option><option value="public">Public</option></select></label><button className="primary-button" onClick={()=>app.setData(d=>({...d,settings}))}>Save changes</button><button className="danger-button" onClick={app.reset}>Reset demo content</button></div></section></div></div>}
